package strings_and_dialogs;

import javax.swing.JOptionPane;

public class MorningZombie {
public static void main(String[] args) {
	JOptionPane.showMessageDialog(null, "Wake up");
	JOptionPane.showMessageDialog(null, "Decide you don't need to go to school");
	JOptionPane.showMessageDialog(null, "Go back to sleep");
	JOptionPane.showMessageDialog(null, "Realize the finals are today");
	JOptionPane.showMessageDialog(null, "Jump out of bed");
	JOptionPane.showMessageDialog(null, "Get dressed");
	JOptionPane.showMessageDialog(null, "Run out of house");
	JOptionPane.showMessageDialog(null, "Steal neighbor's bike and bike to Ferrari dealership");
	JOptionPane.showMessageDialog(null, "Hotwire a Ferrari");
	JOptionPane.showMessageDialog(null, "Get into a police chase");
	JOptionPane.showMessageDialog(null, "Drive to US-Mexican border");
	JOptionPane.showMessageDialog(null, "Smash through border fence");
	JOptionPane.showMessageDialog(null, "Get chased by border control and Mexican police");
	JOptionPane.showMessageDialog(null, "Drive to a port");
	JOptionPane.showMessageDialog(null, "Hijack a speedboat");
	JOptionPane.showMessageDialog(null, "Drive the speedboat to a cruise ship");
	JOptionPane.showMessageDialog(null, "Hijack cruise ship");
	JOptionPane.showMessageDialog(null, "Drive cruise ship to Russia");
	JOptionPane.showMessageDialog(null, "Crash cruise ship");
	JOptionPane.showMessageDialog(null, "Swim to Russia");
	JOptionPane.showMessageDialog(null, "Hotwire a car");
	JOptionPane.showMessageDialog(null, "Drive to nearest space shuttle launch site");
	JOptionPane.showMessageDialog(null, "Get on a rocket");
	JOptionPane.showMessageDialog(null, "Blast off");
	JOptionPane.showMessageDialog(null, "Realize you got on a nuke for some reason");
	JOptionPane.showMessageDialog(null, "Nuke is headed to Washington DC");
	JOptionPane.showMessageDialog(null, "Crash into the White House and die in a glorious explosion");
	JOptionPane.showMessageDialog(null, "Wake up");
	JOptionPane.showMessageDialog(null, "Realize all that happened was just a dream");
	JOptionPane.showMessageDialog(null, "Decide you don't need to go to school");
	JOptionPane.showMessageDialog(null, "Go back to sleep");
	JOptionPane.showMessageDialog(null, "Realize the finals are today");
	JOptionPane.showMessageDialog(null, "Jump out of bed");
	JOptionPane.showMessageDialog(null, "Get dressed");
	JOptionPane.showMessageDialog(null, "Run out of house");
	JOptionPane.showMessageDialog(null, "Steal neighbor's bike and bike to Ferrari dealership");
	JOptionPane.showMessageDialog(null, "Hotwire a Ferrari");
	JOptionPane.showMessageDialog(null, "Get into a police chase");
	JOptionPane.showMessageDialog(null, "Drive to US-Mexican border");
	JOptionPane.showMessageDialog(null, "Smash through border fence");
	JOptionPane.showMessageDialog(null, "Get chased by border control and Mexican police");
	JOptionPane.showMessageDialog(null, "Drive to a port");
	JOptionPane.showMessageDialog(null, "Hijack a speedboat");
	JOptionPane.showMessageDialog(null, "Drive the speedboat to a cruise ship");
	JOptionPane.showMessageDialog(null, "Hijack cruise ship");
	JOptionPane.showMessageDialog(null, "Drive cruise ship to Russia");
	JOptionPane.showMessageDialog(null, "Crash cruise ship");
	JOptionPane.showMessageDialog(null, "Swim to Russia");
	JOptionPane.showMessageDialog(null, "Hotwire a car");
	JOptionPane.showMessageDialog(null, "Drive to nearest space shuttle launch site");
	JOptionPane.showMessageDialog(null, "Get on a rocket");
	JOptionPane.showMessageDialog(null, "Blast off");
	JOptionPane.showMessageDialog(null, "Realize you got on a nuke for some reason");
	JOptionPane.showMessageDialog(null, "Nuke is headed to Washington DC");
	JOptionPane.showMessageDialog(null, "Crash into the White House and die in a glorious explosion");
	JOptionPane.showMessageDialog(null, "Wake up");
	JOptionPane.showMessageDialog(null, "Realize all that happened was just a dream");
	JOptionPane.showMessageDialog(null, "Decide you don't need to go to school");
	JOptionPane.showMessageDialog(null, "Go back to sleep");
	JOptionPane.showMessageDialog(null, "Realize the finals are today");
	JOptionPane.showMessageDialog(null, "Jump out of bed");
	JOptionPane.showMessageDialog(null, "Get dressed");
	JOptionPane.showMessageDialog(null, "Run out of house");
	JOptionPane.showMessageDialog(null, "Steal neighbor's bike and bike to Ferrari dealership");
	JOptionPane.showMessageDialog(null, "Hotwire a Ferrari");
	JOptionPane.showMessageDialog(null, "Get into a police chase");
	JOptionPane.showMessageDialog(null, "Drive to US-Mexican border");
	JOptionPane.showMessageDialog(null, "Smash through border fence");
	JOptionPane.showMessageDialog(null, "Get chased by border control and Mexican police");
	JOptionPane.showMessageDialog(null, "Drive to a port");
	JOptionPane.showMessageDialog(null, "Hijack a speedboat");
	JOptionPane.showMessageDialog(null, "Drive the speedboat to a cruise ship");
	JOptionPane.showMessageDialog(null, "Hijack cruise ship");
	JOptionPane.showMessageDialog(null, "Drive cruise ship to Russia");
	JOptionPane.showMessageDialog(null, "Crash cruise ship");
	JOptionPane.showMessageDialog(null, "Swim to Russia");
	JOptionPane.showMessageDialog(null, "Hotwire a car");
	JOptionPane.showMessageDialog(null, "Drive to nearest space shuttle launch site");
	JOptionPane.showMessageDialog(null, "Get on a rocket");
	JOptionPane.showMessageDialog(null, "Blast off");
	JOptionPane.showMessageDialog(null, "Realize you got on a nuke for some reason");
	JOptionPane.showMessageDialog(null, "Nuke is headed to Washington DC");
	JOptionPane.showMessageDialog(null, "Crash into the White House and die in a glorious explosion");
	JOptionPane.showMessageDialog(null, "Wake up");
	JOptionPane.showMessageDialog(null, "Realize all that happened was just a dream");
	JOptionPane.showMessageDialog(null, "Decide you don't need to go to school");
	JOptionPane.showMessageDialog(null, "Go back to sleep");
	JOptionPane.showMessageDialog(null, "Realize the finals are today");
	JOptionPane.showMessageDialog(null, "Jump out of bed");
	JOptionPane.showMessageDialog(null, "Get dressed");
	JOptionPane.showMessageDialog(null, "Run out of house");
	JOptionPane.showMessageDialog(null, "Steal neighbor's bike and bike to Ferrari dealership");
	JOptionPane.showMessageDialog(null, "Hotwire a Ferrari");
	JOptionPane.showMessageDialog(null, "Get into a police chase");
	JOptionPane.showMessageDialog(null, "Drive to US-Mexican border");
	JOptionPane.showMessageDialog(null, "Smash through border fence");
	JOptionPane.showMessageDialog(null, "Get chased by border control and Mexican police");
	JOptionPane.showMessageDialog(null, "Drive to a port");
	JOptionPane.showMessageDialog(null, "Hijack a speedboat");
	JOptionPane.showMessageDialog(null, "Drive the speedboat to a cruise ship");
	JOptionPane.showMessageDialog(null, "Hijack cruise ship");
	JOptionPane.showMessageDialog(null, "Drive cruise ship to Russia");
	JOptionPane.showMessageDialog(null, "Crash cruise ship");
	JOptionPane.showMessageDialog(null, "Swim to Russia");
	JOptionPane.showMessageDialog(null, "Hotwire a car");
	JOptionPane.showMessageDialog(null, "Drive to nearest space shuttle launch site");
	JOptionPane.showMessageDialog(null, "Get on a rocket");
	JOptionPane.showMessageDialog(null, "Blast off");
	JOptionPane.showMessageDialog(null, "Realize you got on a nuke for some reason");
	JOptionPane.showMessageDialog(null, "Nuke is headed to Washington DC");
	JOptionPane.showMessageDialog(null, "Crash into the White House and die in a glorious explosion");
	JOptionPane.showMessageDialog(null, "Wake up");
	JOptionPane.showMessageDialog(null, "Realize all that happened was just a dream");
	JOptionPane.showMessageDialog(null, "Decide you don't need to go to school");
	JOptionPane.showMessageDialog(null, "Go back to sleep");
	JOptionPane.showMessageDialog(null, "Realize the finals are today");
	JOptionPane.showMessageDialog(null, "Jump out of bed");
	JOptionPane.showMessageDialog(null, "Get dressed");
	JOptionPane.showMessageDialog(null, "Run out of house");
	JOptionPane.showMessageDialog(null, "Steal neighbor's bike and bike to Ferrari dealership");
	JOptionPane.showMessageDialog(null, "Hotwire a Ferrari");
	JOptionPane.showMessageDialog(null, "Get into a police chase");
	JOptionPane.showMessageDialog(null, "Drive to US-Mexican border");
	JOptionPane.showMessageDialog(null, "Smash through border fence");
	JOptionPane.showMessageDialog(null, "Get chased by border control and Mexican police");
	JOptionPane.showMessageDialog(null, "Drive to a port");
	JOptionPane.showMessageDialog(null, "Hijack a speedboat");
	JOptionPane.showMessageDialog(null, "Drive the speedboat to a cruise ship");
	JOptionPane.showMessageDialog(null, "Hijack cruise ship");
	JOptionPane.showMessageDialog(null, "Drive cruise ship to Russia");
	JOptionPane.showMessageDialog(null, "Crash cruise ship");
	JOptionPane.showMessageDialog(null, "Swim to Russia");
	JOptionPane.showMessageDialog(null, "Hotwire a car");
	JOptionPane.showMessageDialog(null, "Drive to nearest space shuttle launch site");
	JOptionPane.showMessageDialog(null, "Get on a rocket");
	JOptionPane.showMessageDialog(null, "Blast off");
	JOptionPane.showMessageDialog(null, "Realize you got on a nuke for some reason");
	JOptionPane.showMessageDialog(null, "Nuke is headed to Washington DC");
	JOptionPane.showMessageDialog(null, "Crash into the White House and die in a glorious explosion");
	JOptionPane.showMessageDialog(null, "Wake up");
	JOptionPane.showMessageDialog(null, "Realize all that happened was just a dream");
	JOptionPane.showMessageDialog(null, "Decide you don't need to go to school");
	JOptionPane.showMessageDialog(null, "Go back to sleep");
	JOptionPane.showMessageDialog(null, "Realize the finals are today");
	JOptionPane.showMessageDialog(null, "Jump out of bed");
	JOptionPane.showMessageDialog(null, "Get dressed");
	JOptionPane.showMessageDialog(null, "Run out of house");
	JOptionPane.showMessageDialog(null, "Steal neighbor's bike and bike to Ferrari dealership");
	JOptionPane.showMessageDialog(null, "Hotwire a Ferrari");
	JOptionPane.showMessageDialog(null, "Get into a police chase");
	JOptionPane.showMessageDialog(null, "Drive to US-Mexican border");
	JOptionPane.showMessageDialog(null, "Smash through border fence");
	JOptionPane.showMessageDialog(null, "Get chased by border control and Mexican police");
	JOptionPane.showMessageDialog(null, "Drive to a port");
	JOptionPane.showMessageDialog(null, "Hijack a speedboat");
	JOptionPane.showMessageDialog(null, "Drive the speedboat to a cruise ship");
	JOptionPane.showMessageDialog(null, "Hijack cruise ship");
	JOptionPane.showMessageDialog(null, "Drive cruise ship to Russia");
	JOptionPane.showMessageDialog(null, "Crash cruise ship");
	JOptionPane.showMessageDialog(null, "Swim to Russia");
	JOptionPane.showMessageDialog(null, "Hotwire a car");
	JOptionPane.showMessageDialog(null, "Drive to nearest space shuttle launch site");
	JOptionPane.showMessageDialog(null, "Get on a rocket");
	JOptionPane.showMessageDialog(null, "Blast off");
	JOptionPane.showMessageDialog(null, "Realize you got on a nuke for some reason");
	JOptionPane.showMessageDialog(null, "Nuke is headed to Washington DC");
	JOptionPane.showMessageDialog(null, "Crash into the White House and die in a glorious explosion");
	JOptionPane.showMessageDialog(null, "Wake up");
	JOptionPane.showMessageDialog(null, "Realize all that happened was just a dream");
	JOptionPane.showMessageDialog(null, "Decide you don't need to go to school");
	JOptionPane.showMessageDialog(null, "Go back to sleep");
	JOptionPane.showMessageDialog(null, "Realize the finals are today");
	JOptionPane.showMessageDialog(null, "Jump out of bed");
	JOptionPane.showMessageDialog(null, "Get dressed");
	JOptionPane.showMessageDialog(null, "Run out of house");
	JOptionPane.showMessageDialog(null, "Steal neighbor's bike and bike to Ferrari dealership");
	JOptionPane.showMessageDialog(null, "Hotwire a Ferrari");
	JOptionPane.showMessageDialog(null, "Get into a police chase");
	JOptionPane.showMessageDialog(null, "Drive to US-Mexican border");
	JOptionPane.showMessageDialog(null, "Smash through border fence");
	JOptionPane.showMessageDialog(null, "Get chased by border control and Mexican police");
	JOptionPane.showMessageDialog(null, "Drive to a port");
	JOptionPane.showMessageDialog(null, "Hijack a speedboat");
	JOptionPane.showMessageDialog(null, "Drive the speedboat to a cruise ship");
	JOptionPane.showMessageDialog(null, "Hijack cruise ship");
	JOptionPane.showMessageDialog(null, "Drive cruise ship to Russia");
	JOptionPane.showMessageDialog(null, "Crash cruise ship");
	JOptionPane.showMessageDialog(null, "Swim to Russia");
	JOptionPane.showMessageDialog(null, "Hotwire a car");
	JOptionPane.showMessageDialog(null, "Drive to nearest space shuttle launch site");
	JOptionPane.showMessageDialog(null, "Get on a rocket");
	JOptionPane.showMessageDialog(null, "Blast off");
	JOptionPane.showMessageDialog(null, "Realize you got on a nuke for some reason");
	JOptionPane.showMessageDialog(null, "Nuke is headed to Washington DC");
	JOptionPane.showMessageDialog(null, "Crash into the White House and die in a glorious explosion");
	JOptionPane.showMessageDialog(null, "Wake up");
	JOptionPane.showMessageDialog(null, "Realize all that happened was just a dream");
	JOptionPane.showMessageDialog(null, "Decide you don't need to go to school");
	JOptionPane.showMessageDialog(null, "Go back to sleep");
	JOptionPane.showMessageDialog(null, "Realize the finals are today");
	JOptionPane.showMessageDialog(null, "Jump out of bed");
	JOptionPane.showMessageDialog(null, "Get dressed");
	JOptionPane.showMessageDialog(null, "Run out of house");
	JOptionPane.showMessageDialog(null, "Steal neighbor's bike and bike to Ferrari dealership");
	JOptionPane.showMessageDialog(null, "Hotwire a Ferrari");
	JOptionPane.showMessageDialog(null, "Get into a police chase");
	JOptionPane.showMessageDialog(null, "Drive to US-Mexican border");
	JOptionPane.showMessageDialog(null, "Smash through border fence");
	JOptionPane.showMessageDialog(null, "Get chased by border control and Mexican police");
	JOptionPane.showMessageDialog(null, "Drive to a port");
	JOptionPane.showMessageDialog(null, "Hijack a speedboat");
	JOptionPane.showMessageDialog(null, "Drive the speedboat to a cruise ship");
	JOptionPane.showMessageDialog(null, "Hijack cruise ship");
	JOptionPane.showMessageDialog(null, "Drive cruise ship to Russia");
	JOptionPane.showMessageDialog(null, "Crash cruise ship");
	JOptionPane.showMessageDialog(null, "Swim to Russia");
	JOptionPane.showMessageDialog(null, "Hotwire a car");
	JOptionPane.showMessageDialog(null, "Drive to nearest space shuttle launch site");
	JOptionPane.showMessageDialog(null, "Get on a rocket");
	JOptionPane.showMessageDialog(null, "Blast off");
	JOptionPane.showMessageDialog(null, "Realize you got on a nuke for some reason");
	JOptionPane.showMessageDialog(null, "Nuke is headed to Washington DC");
	JOptionPane.showMessageDialog(null, "Crash into the White House and die in a glorious explosion");
	JOptionPane.showMessageDialog(null, "Wake up");
	JOptionPane.showMessageDialog(null, "Realize all that happened was just a dream");
	JOptionPane.showMessageDialog(null, "Decide you don't need to go to school");
	JOptionPane.showMessageDialog(null, "Go back to sleep");
	JOptionPane.showMessageDialog(null, "Realize the finals are today");
	JOptionPane.showMessageDialog(null, "Jump out of bed");
	JOptionPane.showMessageDialog(null, "Get dressed");
	JOptionPane.showMessageDialog(null, "Run out of house");
	JOptionPane.showMessageDialog(null, "Steal neighbor's bike and bike to Ferrari dealership");
	JOptionPane.showMessageDialog(null, "Hotwire a Ferrari");
	JOptionPane.showMessageDialog(null, "Get into a police chase");
	JOptionPane.showMessageDialog(null, "Drive to US-Mexican border");
	JOptionPane.showMessageDialog(null, "Smash through border fence");
	JOptionPane.showMessageDialog(null, "Get chased by border control and Mexican police");
	JOptionPane.showMessageDialog(null, "Drive to a port");
	JOptionPane.showMessageDialog(null, "Hijack a speedboat");
	JOptionPane.showMessageDialog(null, "Drive the speedboat to a cruise ship");
	JOptionPane.showMessageDialog(null, "Hijack cruise ship");
	JOptionPane.showMessageDialog(null, "Drive cruise ship to Russia");
	JOptionPane.showMessageDialog(null, "Crash cruise ship");
	JOptionPane.showMessageDialog(null, "Swim to Russia");
	JOptionPane.showMessageDialog(null, "Hotwire a car");
	JOptionPane.showMessageDialog(null, "Drive to nearest space shuttle launch site");
	JOptionPane.showMessageDialog(null, "Get on a rocket");
	JOptionPane.showMessageDialog(null, "Blast off");
	JOptionPane.showMessageDialog(null, "Realize you got on a nuke for some reason");
	JOptionPane.showMessageDialog(null, "Nuke is headed to Washington DC");
	JOptionPane.showMessageDialog(null, "Crash into the White House and die in a glorious explosion");
	JOptionPane.showMessageDialog(null, "Wake up");
	JOptionPane.showMessageDialog(null, "Realize all that happened was just a dream");
	JOptionPane.showMessageDialog(null, "Decide you don't need to go to school");
	JOptionPane.showMessageDialog(null, "Go back to sleep");
	JOptionPane.showMessageDialog(null, "Realize the finals are today");
	JOptionPane.showMessageDialog(null, "Jump out of bed");
	JOptionPane.showMessageDialog(null, "Get dressed");
	JOptionPane.showMessageDialog(null, "Run out of house");
	JOptionPane.showMessageDialog(null, "Steal neighbor's bike and bike to Ferrari dealership");
	JOptionPane.showMessageDialog(null, "Hotwire a Ferrari");
	JOptionPane.showMessageDialog(null, "Get into a police chase");
	JOptionPane.showMessageDialog(null, "Drive to US-Mexican border");
	JOptionPane.showMessageDialog(null, "Smash through border fence");
	JOptionPane.showMessageDialog(null, "Get chased by border control and Mexican police");
	JOptionPane.showMessageDialog(null, "Drive to a port");
	JOptionPane.showMessageDialog(null, "Hijack a speedboat");
	JOptionPane.showMessageDialog(null, "Drive the speedboat to a cruise ship");
	JOptionPane.showMessageDialog(null, "Hijack cruise ship");
	JOptionPane.showMessageDialog(null, "Drive cruise ship to Russia");
	JOptionPane.showMessageDialog(null, "Crash cruise ship");
	JOptionPane.showMessageDialog(null, "Swim to Russia");
	JOptionPane.showMessageDialog(null, "Hotwire a car");
	JOptionPane.showMessageDialog(null, "Drive to nearest space shuttle launch site");
	JOptionPane.showMessageDialog(null, "Get on a rocket");
	JOptionPane.showMessageDialog(null, "Blast off");
	JOptionPane.showMessageDialog(null, "Realize you got on a nuke for some reason");
	JOptionPane.showMessageDialog(null, "Nuke is headed to Washington DC");
	JOptionPane.showMessageDialog(null, "Crash into the White House and die in a glorious explosion");
	JOptionPane.showMessageDialog(null, "Wake up");
	JOptionPane.showMessageDialog(null, "Realize all that happened was just a dream");
	JOptionPane.showMessageDialog(null, "Decide you don't need to go to school");
	JOptionPane.showMessageDialog(null, "Go back to sleep");
	JOptionPane.showMessageDialog(null, "Realize the finals are today");
	JOptionPane.showMessageDialog(null, "Jump out of bed");
	JOptionPane.showMessageDialog(null, "Get dressed");
	JOptionPane.showMessageDialog(null, "Run out of house");
	JOptionPane.showMessageDialog(null, "Steal neighbor's bike and bike to Ferrari dealership");
	JOptionPane.showMessageDialog(null, "Hotwire a Ferrari");
	JOptionPane.showMessageDialog(null, "Get into a police chase");
	JOptionPane.showMessageDialog(null, "Drive to US-Mexican border");
	JOptionPane.showMessageDialog(null, "Smash through border fence");
	JOptionPane.showMessageDialog(null, "Get chased by border control and Mexican police");
	JOptionPane.showMessageDialog(null, "Drive to a port");
	JOptionPane.showMessageDialog(null, "Hijack a speedboat");
	JOptionPane.showMessageDialog(null, "Drive the speedboat to a cruise ship");
	JOptionPane.showMessageDialog(null, "Hijack cruise ship");
	JOptionPane.showMessageDialog(null, "Drive cruise ship to Russia");
	JOptionPane.showMessageDialog(null, "Crash cruise ship");
	JOptionPane.showMessageDialog(null, "Swim to Russia");
	JOptionPane.showMessageDialog(null, "Hotwire a car");
	JOptionPane.showMessageDialog(null, "Drive to nearest space shuttle launch site");
	JOptionPane.showMessageDialog(null, "Get on a rocket");
	JOptionPane.showMessageDialog(null, "Blast off");
	JOptionPane.showMessageDialog(null, "Realize you got on a nuke for some reason");
	JOptionPane.showMessageDialog(null, "Nuke is headed to Washington DC");
	JOptionPane.showMessageDialog(null, "Crash into the White House and die in a glorious explosion");
	JOptionPane.showMessageDialog(null, "Wake up");
	JOptionPane.showMessageDialog(null, "Realize all that happened was just a dream");
	JOptionPane.showMessageDialog(null, "Decide you don't need to go to school");
	JOptionPane.showMessageDialog(null, "Go back to sleep");
	JOptionPane.showMessageDialog(null, "Realize the finals are today");
	JOptionPane.showMessageDialog(null, "Jump out of bed");
	JOptionPane.showMessageDialog(null, "Get dressed");
	JOptionPane.showMessageDialog(null, "Run out of house");
	JOptionPane.showMessageDialog(null, "Steal neighbor's bike and bike to Ferrari dealership");
	JOptionPane.showMessageDialog(null, "Hotwire a Ferrari");
	JOptionPane.showMessageDialog(null, "Get into a police chase");
	JOptionPane.showMessageDialog(null, "Drive to US-Mexican border");
	JOptionPane.showMessageDialog(null, "Smash through border fence");
	JOptionPane.showMessageDialog(null, "Get chased by border control and Mexican police");
	JOptionPane.showMessageDialog(null, "Drive to a port");
	JOptionPane.showMessageDialog(null, "Hijack a speedboat");
	JOptionPane.showMessageDialog(null, "Drive the speedboat to a cruise ship");
	JOptionPane.showMessageDialog(null, "Hijack cruise ship");
	JOptionPane.showMessageDialog(null, "Drive cruise ship to Russia");
	JOptionPane.showMessageDialog(null, "Crash cruise ship");
	JOptionPane.showMessageDialog(null, "Swim to Russia");
	JOptionPane.showMessageDialog(null, "Hotwire a car");
	JOptionPane.showMessageDialog(null, "Drive to nearest space shuttle launch site");
	JOptionPane.showMessageDialog(null, "Get on a rocket");
	JOptionPane.showMessageDialog(null, "Blast off");
	JOptionPane.showMessageDialog(null, "Realize you got on a nuke for some reason");
	JOptionPane.showMessageDialog(null, "Nuke is headed to Washington DC");
	JOptionPane.showMessageDialog(null, "Crash into the White House and die in a glorious explosion");
	JOptionPane.showMessageDialog(null, "Wake up");
	JOptionPane.showMessageDialog(null, "Realize all that happened was just a dream");
	JOptionPane.showMessageDialog(null, "Decide you don't need to go to school");
	JOptionPane.showMessageDialog(null, "Go back to sleep");
	JOptionPane.showMessageDialog(null, "Realize the finals are today");
	JOptionPane.showMessageDialog(null, "Jump out of bed");
	JOptionPane.showMessageDialog(null, "Get dressed");
	JOptionPane.showMessageDialog(null, "Run out of house");
	JOptionPane.showMessageDialog(null, "Steal neighbor's bike and bike to Ferrari dealership");
	JOptionPane.showMessageDialog(null, "Hotwire a Ferrari");
	JOptionPane.showMessageDialog(null, "Get into a police chase");
	JOptionPane.showMessageDialog(null, "Drive to US-Mexican border");
	JOptionPane.showMessageDialog(null, "Smash through border fence");
	JOptionPane.showMessageDialog(null, "Get chased by border control and Mexican police");
	JOptionPane.showMessageDialog(null, "Drive to a port");
	JOptionPane.showMessageDialog(null, "Hijack a speedboat");
	JOptionPane.showMessageDialog(null, "Drive the speedboat to a cruise ship");
	JOptionPane.showMessageDialog(null, "Hijack cruise ship");
	JOptionPane.showMessageDialog(null, "Drive cruise ship to Russia");
	JOptionPane.showMessageDialog(null, "Crash cruise ship");
	JOptionPane.showMessageDialog(null, "Swim to Russia");
	JOptionPane.showMessageDialog(null, "Hotwire a car");
	JOptionPane.showMessageDialog(null, "Drive to nearest space shuttle launch site");
	JOptionPane.showMessageDialog(null, "Get on a rocket");
	JOptionPane.showMessageDialog(null, "Blast off");
	JOptionPane.showMessageDialog(null, "Realize you got on a nuke for some reason");
	JOptionPane.showMessageDialog(null, "Nuke is headed to Washington DC");
	JOptionPane.showMessageDialog(null, "Crash into the White House and die in a glorious explosion");
	JOptionPane.showMessageDialog(null, "Wake up");
	JOptionPane.showMessageDialog(null, "Realize all that happened was just a dream");
	JOptionPane.showMessageDialog(null, "Decide you don't need to go to school");
	JOptionPane.showMessageDialog(null, "Go back to sleep");
	JOptionPane.showMessageDialog(null, "Realize the finals are today");
	JOptionPane.showMessageDialog(null, "Jump out of bed");
	JOptionPane.showMessageDialog(null, "Get dressed");
	JOptionPane.showMessageDialog(null, "Run out of house");
	JOptionPane.showMessageDialog(null, "Steal neighbor's bike and bike to Ferrari dealership");
	JOptionPane.showMessageDialog(null, "Hotwire a Ferrari");
	JOptionPane.showMessageDialog(null, "Get into a police chase");
	JOptionPane.showMessageDialog(null, "Drive to US-Mexican border");
	JOptionPane.showMessageDialog(null, "Smash through border fence");
	JOptionPane.showMessageDialog(null, "Get chased by border control and Mexican police");
	JOptionPane.showMessageDialog(null, "Drive to a port");
	JOptionPane.showMessageDialog(null, "Hijack a speedboat");
	JOptionPane.showMessageDialog(null, "Drive the speedboat to a cruise ship");
	JOptionPane.showMessageDialog(null, "Hijack cruise ship");
	JOptionPane.showMessageDialog(null, "Drive cruise ship to Russia");
	JOptionPane.showMessageDialog(null, "Crash cruise ship");
	JOptionPane.showMessageDialog(null, "Swim to Russia");
	JOptionPane.showMessageDialog(null, "Hotwire a car");
	JOptionPane.showMessageDialog(null, "Drive to nearest space shuttle launch site");
	JOptionPane.showMessageDialog(null, "Get on a rocket");
	JOptionPane.showMessageDialog(null, "Blast off");
	JOptionPane.showMessageDialog(null, "Realize you got on a nuke for some reason");
	JOptionPane.showMessageDialog(null, "Nuke is headed to Washington DC");
	JOptionPane.showMessageDialog(null, "Crash into the White House and die in a glorious explosion");
	JOptionPane.showMessageDialog(null, "Wake up");
	JOptionPane.showMessageDialog(null, "Realize all that happened was just a dream");
	JOptionPane.showMessageDialog(null, "Decide you don't need to go to school");
	JOptionPane.showMessageDialog(null, "Go back to sleep");
	JOptionPane.showMessageDialog(null, "Realize the finals are today");
	JOptionPane.showMessageDialog(null, "Jump out of bed");
	JOptionPane.showMessageDialog(null, "Get dressed");
	JOptionPane.showMessageDialog(null, "Run out of house");
	JOptionPane.showMessageDialog(null, "Steal neighbor's bike and bike to Ferrari dealership");
	JOptionPane.showMessageDialog(null, "Hotwire a Ferrari");
	JOptionPane.showMessageDialog(null, "Get into a police chase");
	JOptionPane.showMessageDialog(null, "Drive to US-Mexican border");
	JOptionPane.showMessageDialog(null, "Smash through border fence");
	JOptionPane.showMessageDialog(null, "Get chased by border control and Mexican police");
	JOptionPane.showMessageDialog(null, "Drive to a port");
	JOptionPane.showMessageDialog(null, "Hijack a speedboat");
	JOptionPane.showMessageDialog(null, "Drive the speedboat to a cruise ship");
	JOptionPane.showMessageDialog(null, "Hijack cruise ship");
	JOptionPane.showMessageDialog(null, "Drive cruise ship to Russia");
	JOptionPane.showMessageDialog(null, "Crash cruise ship");
	JOptionPane.showMessageDialog(null, "Swim to Russia");
	JOptionPane.showMessageDialog(null, "Hotwire a car");
	JOptionPane.showMessageDialog(null, "Drive to nearest space shuttle launch site");
	JOptionPane.showMessageDialog(null, "Get on a rocket");
	JOptionPane.showMessageDialog(null, "Blast off");
	JOptionPane.showMessageDialog(null, "Realize you got on a nuke for some reason");
	JOptionPane.showMessageDialog(null, "Nuke is headed to Washington DC");
	JOptionPane.showMessageDialog(null, "Crash into the White House and die in a glorious explosion");
	JOptionPane.showMessageDialog(null, "Wake up");
	JOptionPane.showMessageDialog(null, "Realize all that happened was just a dream");
	JOptionPane.showMessageDialog(null, "Decide you don't need to go to school");
	JOptionPane.showMessageDialog(null, "Go back to sleep");
	JOptionPane.showMessageDialog(null, "Realize the finals are today");
	JOptionPane.showMessageDialog(null, "Jump out of bed");
	JOptionPane.showMessageDialog(null, "Get dressed");
	JOptionPane.showMessageDialog(null, "Run out of house");
	JOptionPane.showMessageDialog(null, "Steal neighbor's bike and bike to Ferrari dealership");
	JOptionPane.showMessageDialog(null, "Hotwire a Ferrari");
	JOptionPane.showMessageDialog(null, "Get into a police chase");
	JOptionPane.showMessageDialog(null, "Drive to US-Mexican border");
	JOptionPane.showMessageDialog(null, "Smash through border fence");
	JOptionPane.showMessageDialog(null, "Get chased by border control and Mexican police");
	JOptionPane.showMessageDialog(null, "Drive to a port");
	JOptionPane.showMessageDialog(null, "Hijack a speedboat");
	JOptionPane.showMessageDialog(null, "Drive the speedboat to a cruise ship");
	JOptionPane.showMessageDialog(null, "Hijack cruise ship");
	JOptionPane.showMessageDialog(null, "Drive cruise ship to Russia");
	JOptionPane.showMessageDialog(null, "Crash cruise ship");
	JOptionPane.showMessageDialog(null, "Swim to Russia");
	JOptionPane.showMessageDialog(null, "Hotwire a car");
	JOptionPane.showMessageDialog(null, "Drive to nearest space shuttle launch site");
	JOptionPane.showMessageDialog(null, "Get on a rocket");
	JOptionPane.showMessageDialog(null, "Blast off");
	JOptionPane.showMessageDialog(null, "Realize you got on a nuke for some reason");
	JOptionPane.showMessageDialog(null, "Nuke is headed to Washington DC");
	JOptionPane.showMessageDialog(null, "Crash into the White House and die in a glorious explosion");
	JOptionPane.showMessageDialog(null, "Wake up");
	JOptionPane.showMessageDialog(null, "Realize all that happened was just a dream");
	JOptionPane.showMessageDialog(null, "Decide you don't need to go to school");
	JOptionPane.showMessageDialog(null, "Go back to sleep");
	JOptionPane.showMessageDialog(null, "Realize the finals are today");
	JOptionPane.showMessageDialog(null, "Jump out of bed");
	JOptionPane.showMessageDialog(null, "Get dressed");
	JOptionPane.showMessageDialog(null, "Run out of house");
	JOptionPane.showMessageDialog(null, "Steal neighbor's bike and bike to Ferrari dealership");
	JOptionPane.showMessageDialog(null, "Hotwire a Ferrari");
	JOptionPane.showMessageDialog(null, "Get into a police chase");
	JOptionPane.showMessageDialog(null, "Drive to US-Mexican border");
	JOptionPane.showMessageDialog(null, "Smash through border fence");
	JOptionPane.showMessageDialog(null, "Get chased by border control and Mexican police");
	JOptionPane.showMessageDialog(null, "Drive to a port");
	JOptionPane.showMessageDialog(null, "Hijack a speedboat");
	JOptionPane.showMessageDialog(null, "Drive the speedboat to a cruise ship");
	JOptionPane.showMessageDialog(null, "Hijack cruise ship");
	JOptionPane.showMessageDialog(null, "Drive cruise ship to Russia");
	JOptionPane.showMessageDialog(null, "Crash cruise ship");
	JOptionPane.showMessageDialog(null, "Swim to Russia");
	JOptionPane.showMessageDialog(null, "Hotwire a car");
	JOptionPane.showMessageDialog(null, "Drive to nearest space shuttle launch site");
	JOptionPane.showMessageDialog(null, "Get on a rocket");
	JOptionPane.showMessageDialog(null, "Blast off");
	JOptionPane.showMessageDialog(null, "Realize you got on a nuke for some reason");
	JOptionPane.showMessageDialog(null, "Nuke is headed to Washington DC");
	JOptionPane.showMessageDialog(null, "Crash into the White House and die in a glorious explosion");
	JOptionPane.showMessageDialog(null, "Wake up");
	JOptionPane.showMessageDialog(null, "Realize all that happened was just a dream");
	JOptionPane.showMessageDialog(null, "Decide you don't need to go to school");
	JOptionPane.showMessageDialog(null, "Go back to sleep");
	JOptionPane.showMessageDialog(null, "Realize the finals are today");
	JOptionPane.showMessageDialog(null, "Jump out of bed");
	JOptionPane.showMessageDialog(null, "Get dressed");
	JOptionPane.showMessageDialog(null, "Run out of house");
	JOptionPane.showMessageDialog(null, "Steal neighbor's bike and bike to Ferrari dealership");
	JOptionPane.showMessageDialog(null, "Hotwire a Ferrari");
	JOptionPane.showMessageDialog(null, "Get into a police chase");
	JOptionPane.showMessageDialog(null, "Drive to US-Mexican border");
	JOptionPane.showMessageDialog(null, "Smash through border fence");
	JOptionPane.showMessageDialog(null, "Get chased by border control and Mexican police");
	JOptionPane.showMessageDialog(null, "Drive to a port");
	JOptionPane.showMessageDialog(null, "Hijack a speedboat");
	JOptionPane.showMessageDialog(null, "Drive the speedboat to a cruise ship");
	JOptionPane.showMessageDialog(null, "Hijack cruise ship");
	JOptionPane.showMessageDialog(null, "Drive cruise ship to Russia");
	JOptionPane.showMessageDialog(null, "Crash cruise ship");
	JOptionPane.showMessageDialog(null, "Swim to Russia");
	JOptionPane.showMessageDialog(null, "Hotwire a car");
	JOptionPane.showMessageDialog(null, "Drive to nearest space shuttle launch site");
	JOptionPane.showMessageDialog(null, "Get on a rocket");
	JOptionPane.showMessageDialog(null, "Blast off");
	JOptionPane.showMessageDialog(null, "Realize you got on a nuke for some reason");
	JOptionPane.showMessageDialog(null, "Nuke is headed to Washington DC");
	JOptionPane.showMessageDialog(null, "Crash into the White House and die in a glorious explosion");
}
}
